name: Publish

on:
  push:
    # Publish `v*` tags as releases.
    tags:
    - v*
  pull_request:

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.9.x
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.3'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

  # Push image to GitHub Container Registry and Docker Hub
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    # Ensure test job passes before pushing image.
    needs: test
    steps:
    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.APPLICATION }},ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.APPLICATION }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        build-args: VERSION=${{ steps.meta.outputs.tag }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}